/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMembrosRouteImport } from './routes/_app/membros'
import { Route as AppContaRouteImport } from './routes/_app/conta'
import { Route as AppConselhosRouteImport } from './routes/_app/conselhos'
import { Route as AppOrixasIndexRouteImport } from './routes/_app/orixas.index'
import { Route as AppOracoesIndexRouteImport } from './routes/_app/oracoes/index'
import { Route as AppEstudosIndexRouteImport } from './routes/_app/estudos/index'
import { Route as AppEntidadesIndexRouteImport } from './routes/_app/entidades.index'
import { Route as AppOrixasSlugRouteImport } from './routes/_app/orixas.$slug'
import { Route as AppOracoesSlugRouteImport } from './routes/_app/oracoes/$slug'
import { Route as AppEstudosSlugRouteImport } from './routes/_app/estudos/$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConselhosRoute = AppConselhosRouteImport.update({
  id: '/conselhos',
  path: '/conselhos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrixasIndexRoute = AppOrixasIndexRouteImport.update({
  id: '/orixas/',
  path: '/orixas/',
  getParentRoute: () => AppRoute,
} as any)
const AppOracoesIndexRoute = AppOracoesIndexRouteImport.update({
  id: '/oracoes/',
  path: '/oracoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosIndexRoute = AppEstudosIndexRouteImport.update({
  id: '/estudos/',
  path: '/estudos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntidadesIndexRoute = AppEntidadesIndexRouteImport.update({
  id: '/entidades/',
  path: '/entidades/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrixasSlugRoute = AppOrixasSlugRouteImport.update({
  id: '/orixas/$slug',
  path: '/orixas/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppOracoesSlugRoute = AppOracoesSlugRouteImport.update({
  id: '/oracoes/$slug',
  path: '/oracoes/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosSlugRoute = AppEstudosSlugRouteImport.update({
  id: '/estudos/$slug',
  path: '/estudos/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/conselhos': typeof AppConselhosRoute
  '/conta': typeof AppContaRoute
  '/membros': typeof AppMembrosRoute
  '/estudos/$slug': typeof AppEstudosSlugRoute
  '/oracoes/$slug': typeof AppOracoesSlugRoute
  '/orixas/$slug': typeof AppOrixasSlugRoute
  '/entidades/': typeof AppEntidadesIndexRoute
  '/estudos/': typeof AppEstudosIndexRoute
  '/oracoes/': typeof AppOracoesIndexRoute
  '/orixas/': typeof AppOrixasIndexRoute
}
export interface FileRoutesByTo {
  '/conselhos': typeof AppConselhosRoute
  '/conta': typeof AppContaRoute
  '/membros': typeof AppMembrosRoute
  '/': typeof AppIndexRoute
  '/estudos/$slug': typeof AppEstudosSlugRoute
  '/oracoes/$slug': typeof AppOracoesSlugRoute
  '/orixas/$slug': typeof AppOrixasSlugRoute
  '/entidades': typeof AppEntidadesIndexRoute
  '/estudos': typeof AppEstudosIndexRoute
  '/oracoes': typeof AppOracoesIndexRoute
  '/orixas': typeof AppOrixasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/conselhos': typeof AppConselhosRoute
  '/_app/conta': typeof AppContaRoute
  '/_app/membros': typeof AppMembrosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/estudos/$slug': typeof AppEstudosSlugRoute
  '/_app/oracoes/$slug': typeof AppOracoesSlugRoute
  '/_app/orixas/$slug': typeof AppOrixasSlugRoute
  '/_app/entidades/': typeof AppEntidadesIndexRoute
  '/_app/estudos/': typeof AppEstudosIndexRoute
  '/_app/oracoes/': typeof AppOracoesIndexRoute
  '/_app/orixas/': typeof AppOrixasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conselhos'
    | '/conta'
    | '/membros'
    | '/estudos/$slug'
    | '/oracoes/$slug'
    | '/orixas/$slug'
    | '/entidades/'
    | '/estudos/'
    | '/oracoes/'
    | '/orixas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/conselhos'
    | '/conta'
    | '/membros'
    | '/'
    | '/estudos/$slug'
    | '/oracoes/$slug'
    | '/orixas/$slug'
    | '/entidades'
    | '/estudos'
    | '/oracoes'
    | '/orixas'
  id:
    | '__root__'
    | '/_app'
    | '/_app/conselhos'
    | '/_app/conta'
    | '/_app/membros'
    | '/_app/'
    | '/_app/estudos/$slug'
    | '/_app/oracoes/$slug'
    | '/_app/orixas/$slug'
    | '/_app/entidades/'
    | '/_app/estudos/'
    | '/_app/oracoes/'
    | '/_app/orixas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membros': {
      id: '/_app/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta': {
      id: '/_app/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conselhos': {
      id: '/_app/conselhos'
      path: '/conselhos'
      fullPath: '/conselhos'
      preLoaderRoute: typeof AppConselhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orixas/': {
      id: '/_app/orixas/'
      path: '/orixas'
      fullPath: '/orixas/'
      preLoaderRoute: typeof AppOrixasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracoes/': {
      id: '/_app/oracoes/'
      path: '/oracoes'
      fullPath: '/oracoes/'
      preLoaderRoute: typeof AppOracoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/': {
      id: '/_app/estudos/'
      path: '/estudos'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AppEstudosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entidades/': {
      id: '/_app/entidades/'
      path: '/entidades'
      fullPath: '/entidades/'
      preLoaderRoute: typeof AppEntidadesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orixas/$slug': {
      id: '/_app/orixas/$slug'
      path: '/orixas/$slug'
      fullPath: '/orixas/$slug'
      preLoaderRoute: typeof AppOrixasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracoes/$slug': {
      id: '/_app/oracoes/$slug'
      path: '/oracoes/$slug'
      fullPath: '/oracoes/$slug'
      preLoaderRoute: typeof AppOracoesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/$slug': {
      id: '/_app/estudos/$slug'
      path: '/estudos/$slug'
      fullPath: '/estudos/$slug'
      preLoaderRoute: typeof AppEstudosSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConselhosRoute: typeof AppConselhosRoute
  AppContaRoute: typeof AppContaRoute
  AppMembrosRoute: typeof AppMembrosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEstudosSlugRoute: typeof AppEstudosSlugRoute
  AppOracoesSlugRoute: typeof AppOracoesSlugRoute
  AppOrixasSlugRoute: typeof AppOrixasSlugRoute
  AppEntidadesIndexRoute: typeof AppEntidadesIndexRoute
  AppEstudosIndexRoute: typeof AppEstudosIndexRoute
  AppOracoesIndexRoute: typeof AppOracoesIndexRoute
  AppOrixasIndexRoute: typeof AppOrixasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConselhosRoute: AppConselhosRoute,
  AppContaRoute: AppContaRoute,
  AppMembrosRoute: AppMembrosRoute,
  AppIndexRoute: AppIndexRoute,
  AppEstudosSlugRoute: AppEstudosSlugRoute,
  AppOracoesSlugRoute: AppOracoesSlugRoute,
  AppOrixasSlugRoute: AppOrixasSlugRoute,
  AppEntidadesIndexRoute: AppEntidadesIndexRoute,
  AppEstudosIndexRoute: AppEstudosIndexRoute,
  AppOracoesIndexRoute: AppOracoesIndexRoute,
  AppOrixasIndexRoute: AppOrixasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
