/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMembrosRouteImport } from './routes/_app/membros'
import { Route as AppContaRouteImport } from './routes/_app/conta'
import { Route as AppConselhosRouteImport } from './routes/_app/conselhos'
import { Route as AppAssinaturaRouteImport } from './routes/_app/assinatura'
import { Route as AppOrixasIndexRouteImport } from './routes/_app/orixas.index'
import { Route as AppOracoesIndexRouteImport } from './routes/_app/oracoes/index'
import { Route as AppEstudosIndexRouteImport } from './routes/_app/estudos/index'
import { Route as AppEsquerdaIndexRouteImport } from './routes/_app/esquerda.index'
import { Route as AppEntidadesIndexRouteImport } from './routes/_app/entidades.index'
import { Route as AppOrixasSlugRouteImport } from './routes/_app/orixas.$slug'
import { Route as AppOracoesSlugRouteImport } from './routes/_app/oracoes/$slug'
import { Route as AppEstudosBibliotecaRouteImport } from './routes/_app/estudos/biblioteca'
import { Route as AppEstudosSlugRouteImport } from './routes/_app/estudos/$slug'
import { Route as AppEsquerdaSlugRouteImport } from './routes/_app/esquerda.$slug'
import { Route as AppEntidadesSlugRouteImport } from './routes/_app/entidades.$slug'
import { Route as AppEstudosSlugAulaLessonSlugRouteImport } from './routes/_app/estudos/$slug/aula/$lessonSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConselhosRoute = AppConselhosRouteImport.update({
  id: '/conselhos',
  path: '/conselhos',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppOrixasIndexRoute = AppOrixasIndexRouteImport.update({
  id: '/orixas/',
  path: '/orixas/',
  getParentRoute: () => AppRoute,
} as any)
const AppOracoesIndexRoute = AppOracoesIndexRouteImport.update({
  id: '/oracoes/',
  path: '/oracoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosIndexRoute = AppEstudosIndexRouteImport.update({
  id: '/estudos/',
  path: '/estudos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEsquerdaIndexRoute = AppEsquerdaIndexRouteImport.update({
  id: '/esquerda/',
  path: '/esquerda/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntidadesIndexRoute = AppEntidadesIndexRouteImport.update({
  id: '/entidades/',
  path: '/entidades/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrixasSlugRoute = AppOrixasSlugRouteImport.update({
  id: '/orixas/$slug',
  path: '/orixas/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppOracoesSlugRoute = AppOracoesSlugRouteImport.update({
  id: '/oracoes/$slug',
  path: '/oracoes/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosBibliotecaRoute = AppEstudosBibliotecaRouteImport.update({
  id: '/estudos/biblioteca',
  path: '/estudos/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosSlugRoute = AppEstudosSlugRouteImport.update({
  id: '/estudos/$slug',
  path: '/estudos/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEsquerdaSlugRoute = AppEsquerdaSlugRouteImport.update({
  id: '/esquerda/$slug',
  path: '/esquerda/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEntidadesSlugRoute = AppEntidadesSlugRouteImport.update({
  id: '/entidades/$slug',
  path: '/entidades/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosSlugAulaLessonSlugRoute =
  AppEstudosSlugAulaLessonSlugRouteImport.update({
    id: '/aula/$lessonSlug',
    path: '/aula/$lessonSlug',
    getParentRoute: () => AppEstudosSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assinatura': typeof AppAssinaturaRoute
  '/conselhos': typeof AppConselhosRoute
  '/conta': typeof AppContaRoute
  '/membros': typeof AppMembrosRoute
  '/entidades/$slug': typeof AppEntidadesSlugRoute
  '/esquerda/$slug': typeof AppEsquerdaSlugRoute
  '/estudos/$slug': typeof AppEstudosSlugRouteWithChildren
  '/estudos/biblioteca': typeof AppEstudosBibliotecaRoute
  '/oracoes/$slug': typeof AppOracoesSlugRoute
  '/orixas/$slug': typeof AppOrixasSlugRoute
  '/entidades/': typeof AppEntidadesIndexRoute
  '/esquerda/': typeof AppEsquerdaIndexRoute
  '/estudos/': typeof AppEstudosIndexRoute
  '/oracoes/': typeof AppOracoesIndexRoute
  '/orixas/': typeof AppOrixasIndexRoute
  '/estudos/$slug/aula/$lessonSlug': typeof AppEstudosSlugAulaLessonSlugRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assinatura': typeof AppAssinaturaRoute
  '/conselhos': typeof AppConselhosRoute
  '/conta': typeof AppContaRoute
  '/membros': typeof AppMembrosRoute
  '/': typeof AppIndexRoute
  '/entidades/$slug': typeof AppEntidadesSlugRoute
  '/esquerda/$slug': typeof AppEsquerdaSlugRoute
  '/estudos/$slug': typeof AppEstudosSlugRouteWithChildren
  '/estudos/biblioteca': typeof AppEstudosBibliotecaRoute
  '/oracoes/$slug': typeof AppOracoesSlugRoute
  '/orixas/$slug': typeof AppOrixasSlugRoute
  '/entidades': typeof AppEntidadesIndexRoute
  '/esquerda': typeof AppEsquerdaIndexRoute
  '/estudos': typeof AppEstudosIndexRoute
  '/oracoes': typeof AppOracoesIndexRoute
  '/orixas': typeof AppOrixasIndexRoute
  '/estudos/$slug/aula/$lessonSlug': typeof AppEstudosSlugAulaLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/assinatura': typeof AppAssinaturaRoute
  '/_app/conselhos': typeof AppConselhosRoute
  '/_app/conta': typeof AppContaRoute
  '/_app/membros': typeof AppMembrosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/entidades/$slug': typeof AppEntidadesSlugRoute
  '/_app/esquerda/$slug': typeof AppEsquerdaSlugRoute
  '/_app/estudos/$slug': typeof AppEstudosSlugRouteWithChildren
  '/_app/estudos/biblioteca': typeof AppEstudosBibliotecaRoute
  '/_app/oracoes/$slug': typeof AppOracoesSlugRoute
  '/_app/orixas/$slug': typeof AppOrixasSlugRoute
  '/_app/entidades/': typeof AppEntidadesIndexRoute
  '/_app/esquerda/': typeof AppEsquerdaIndexRoute
  '/_app/estudos/': typeof AppEstudosIndexRoute
  '/_app/oracoes/': typeof AppOracoesIndexRoute
  '/_app/orixas/': typeof AppOrixasIndexRoute
  '/_app/estudos/$slug/aula/$lessonSlug': typeof AppEstudosSlugAulaLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/assinatura'
    | '/conselhos'
    | '/conta'
    | '/membros'
    | '/entidades/$slug'
    | '/esquerda/$slug'
    | '/estudos/$slug'
    | '/estudos/biblioteca'
    | '/oracoes/$slug'
    | '/orixas/$slug'
    | '/entidades/'
    | '/esquerda/'
    | '/estudos/'
    | '/oracoes/'
    | '/orixas/'
    | '/estudos/$slug/aula/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/assinatura'
    | '/conselhos'
    | '/conta'
    | '/membros'
    | '/'
    | '/entidades/$slug'
    | '/esquerda/$slug'
    | '/estudos/$slug'
    | '/estudos/biblioteca'
    | '/oracoes/$slug'
    | '/orixas/$slug'
    | '/entidades'
    | '/esquerda'
    | '/estudos'
    | '/oracoes'
    | '/orixas'
    | '/estudos/$slug/aula/$lessonSlug'
  id:
    | '__root__'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/assinatura'
    | '/_app/conselhos'
    | '/_app/conta'
    | '/_app/membros'
    | '/_app/'
    | '/_app/entidades/$slug'
    | '/_app/esquerda/$slug'
    | '/_app/estudos/$slug'
    | '/_app/estudos/biblioteca'
    | '/_app/oracoes/$slug'
    | '/_app/orixas/$slug'
    | '/_app/entidades/'
    | '/_app/esquerda/'
    | '/_app/estudos/'
    | '/_app/oracoes/'
    | '/_app/orixas/'
    | '/_app/estudos/$slug/aula/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membros': {
      id: '/_app/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta': {
      id: '/_app/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conselhos': {
      id: '/_app/conselhos'
      path: '/conselhos'
      fullPath: '/conselhos'
      preLoaderRoute: typeof AppConselhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assinatura': {
      id: '/_app/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orixas/': {
      id: '/_app/orixas/'
      path: '/orixas'
      fullPath: '/orixas/'
      preLoaderRoute: typeof AppOrixasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracoes/': {
      id: '/_app/oracoes/'
      path: '/oracoes'
      fullPath: '/oracoes/'
      preLoaderRoute: typeof AppOracoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/': {
      id: '/_app/estudos/'
      path: '/estudos'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AppEstudosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/esquerda/': {
      id: '/_app/esquerda/'
      path: '/esquerda'
      fullPath: '/esquerda/'
      preLoaderRoute: typeof AppEsquerdaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entidades/': {
      id: '/_app/entidades/'
      path: '/entidades'
      fullPath: '/entidades/'
      preLoaderRoute: typeof AppEntidadesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orixas/$slug': {
      id: '/_app/orixas/$slug'
      path: '/orixas/$slug'
      fullPath: '/orixas/$slug'
      preLoaderRoute: typeof AppOrixasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracoes/$slug': {
      id: '/_app/oracoes/$slug'
      path: '/oracoes/$slug'
      fullPath: '/oracoes/$slug'
      preLoaderRoute: typeof AppOracoesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/biblioteca': {
      id: '/_app/estudos/biblioteca'
      path: '/estudos/biblioteca'
      fullPath: '/estudos/biblioteca'
      preLoaderRoute: typeof AppEstudosBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/$slug': {
      id: '/_app/estudos/$slug'
      path: '/estudos/$slug'
      fullPath: '/estudos/$slug'
      preLoaderRoute: typeof AppEstudosSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/esquerda/$slug': {
      id: '/_app/esquerda/$slug'
      path: '/esquerda/$slug'
      fullPath: '/esquerda/$slug'
      preLoaderRoute: typeof AppEsquerdaSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entidades/$slug': {
      id: '/_app/entidades/$slug'
      path: '/entidades/$slug'
      fullPath: '/entidades/$slug'
      preLoaderRoute: typeof AppEntidadesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos/$slug/aula/$lessonSlug': {
      id: '/_app/estudos/$slug/aula/$lessonSlug'
      path: '/aula/$lessonSlug'
      fullPath: '/estudos/$slug/aula/$lessonSlug'
      preLoaderRoute: typeof AppEstudosSlugAulaLessonSlugRouteImport
      parentRoute: typeof AppEstudosSlugRoute
    }
  }
}

interface AppEstudosSlugRouteChildren {
  AppEstudosSlugAulaLessonSlugRoute: typeof AppEstudosSlugAulaLessonSlugRoute
}

const AppEstudosSlugRouteChildren: AppEstudosSlugRouteChildren = {
  AppEstudosSlugAulaLessonSlugRoute: AppEstudosSlugAulaLessonSlugRoute,
}

const AppEstudosSlugRouteWithChildren = AppEstudosSlugRoute._addFileChildren(
  AppEstudosSlugRouteChildren,
)

interface AppRouteChildren {
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppConselhosRoute: typeof AppConselhosRoute
  AppContaRoute: typeof AppContaRoute
  AppMembrosRoute: typeof AppMembrosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntidadesSlugRoute: typeof AppEntidadesSlugRoute
  AppEsquerdaSlugRoute: typeof AppEsquerdaSlugRoute
  AppEstudosSlugRoute: typeof AppEstudosSlugRouteWithChildren
  AppEstudosBibliotecaRoute: typeof AppEstudosBibliotecaRoute
  AppOracoesSlugRoute: typeof AppOracoesSlugRoute
  AppOrixasSlugRoute: typeof AppOrixasSlugRoute
  AppEntidadesIndexRoute: typeof AppEntidadesIndexRoute
  AppEsquerdaIndexRoute: typeof AppEsquerdaIndexRoute
  AppEstudosIndexRoute: typeof AppEstudosIndexRoute
  AppOracoesIndexRoute: typeof AppOracoesIndexRoute
  AppOrixasIndexRoute: typeof AppOrixasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppConselhosRoute: AppConselhosRoute,
  AppContaRoute: AppContaRoute,
  AppMembrosRoute: AppMembrosRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntidadesSlugRoute: AppEntidadesSlugRoute,
  AppEsquerdaSlugRoute: AppEsquerdaSlugRoute,
  AppEstudosSlugRoute: AppEstudosSlugRouteWithChildren,
  AppEstudosBibliotecaRoute: AppEstudosBibliotecaRoute,
  AppOracoesSlugRoute: AppOracoesSlugRoute,
  AppOrixasSlugRoute: AppOrixasSlugRoute,
  AppEntidadesIndexRoute: AppEntidadesIndexRoute,
  AppEsquerdaIndexRoute: AppEsquerdaIndexRoute,
  AppEstudosIndexRoute: AppEstudosIndexRoute,
  AppOracoesIndexRoute: AppOracoesIndexRoute,
  AppOrixasIndexRoute: AppOrixasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
